site_name: ac-backend

plugins:
  #- techdocs-core
  - mermaid2

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.0.2/add-html-label-3fd8c466.min.js

docs_dir: docs
nav:
  - Home: index.md